---
- name: install LAMP server on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install Apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present

    - name: install PHP packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: copy the info.php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php

    - name: restart Apache
      ansible.builtin.systemd:
        name: apache2
        state: restarted
